name: Collect Lighthouse metrics

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Chrome deps
        run: sudo apt-get update ; sudo apt-get install -y chromium-browser unzip
      
      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run and store Lighthouse output
        run: |
          lighthouse --output json --output-path lighthouse/latest.json --chrome-flags="--no-sandbox --headless --disable-gpu" https://seventhirty.dev
          cp lighthouse/latest.json lighthouse/`date +"%y-%m-%d"`.json

      - name: Commit the updated reports
        run: |
          git add lighthouse/
          git config user.name "Automated Github Action"
          git config user.email "<>"
          git commit --message "Update site quality metrics"
          git push origin HEAD:main
